### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by Kubitomakita** [humbug/php-scoper#122]
When I try to run `php-scoper add-prefix` in my simple project I get an Exception:

```
[Symfony\Component\Filesystem\Exception\IOException]                          
Failed to create "C:\www\test\public\wp-content\plugins\asdasdasdsad\buildC:\www\test\public\wp-content\plugins\asdasdasdsad": mkdir(): No such file or directory.   
```

As you can see the path is duplicated. Using output dir / working dir parameters doesn't help.

I'm on Windows 10 using the MINGW64 command line.

**Comment by theofidry** [comment]
Some windows incompatibilities may have sneaked in as:

- the AppVeyor build is failing, not because of the tests but the setup, and I didn't have time to investigate it
- I don't use Windows

Would it be possible for you to investigate where this happens?

**Comment by Kubitomakita** [comment]
Debug says:
```Exception trace:
 () at C:\Users\Kuba\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php:103
 Symfony\Component\Filesystem\Filesystem->mkdir() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php:673
 Symfony\Component\Filesystem\Filesystem->dumpFile() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\humbug\php-scoper\src\Handler\HandleAddPrefix.php:275
 Humbug\PhpScoper\Handler\HandleAddPrefix->scopeFile() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\humbug\php-scoper\src\Handler\HandleAddPrefix.php:219
 Humbug\PhpScoper\Handler\HandleAddPrefix->scopeFiles() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\humbug\php-scoper\src\Handler\HandleAddPrefix.php:72
 Humbug\PhpScoper\Handler\HandleAddPrefix->__invoke() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\humbug\php-scoper\src\Console\Command\AddPrefixCommand.php:163
 Humbug\PhpScoper\Console\Command\AddPrefixCommand->execute() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\symfony\console\Command\Command.php:262
 Symfony\Component\Console\Command\Command->run() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\symfony\console\Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\symfony\console\Application.php:224
 Symfony\Component\Console\Application->doRun() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\symfony\console\Application.php:125
 Symfony\Component\Console\Application->run() at C:\Users\Kuba\AppData\Roaming\Composer\vendor\humbug\php-scoper\bin\php-scoper:37
```

**Comment by theofidry** [comment]
So it's probably coming from [here](https://github.com/humbug/php-scoper/blob/master/src/Handler/HandleAddPrefix.php#L119): it's the function where we collect all the files to scope and calculate the output path

**Comment by Kubitomakita** [comment]
Thanks for the hint. It's actually a `get_common_path()` function problem.

Instead getting:
`C:\www\test\public\wp-content\plugins\asdasdasdsad`

I have:
`\:\www\test\public\wp-content\plugins\asdasdasdsad`

I'm trying to fix this

**Comment by TomasVotruba** [comment]
I think this can be closed for inactivity as well, ref #123

**Comment by theofidry** [comment]
I don't mind leaving the issue open just for visibility, at least if someone opens the issue tab one can see what is left. Since there is only a handful of issues it's fine :)

**Comment by theofidry** [comment]
The most important issues are putted on the 1.0.0 milestones, the others can be dealt with later. Granted that milestones might not grant as much visibility as we might want though

**Comment by TomasVotruba** [comment]
I learned to ignore milestones on issues/PRs, since they're often obsolete and unmaintained. E.g. milestone 1.0.0 on issues, when version 3.2 was released.

I prefer "What you see is what you get." :)

**Comment by tivnet** [comment]
Still does not work under Windows. Same bug with paths.

> In Filesystem.php line 67:
> Failed to create "C:\tmp\sss\buildC:\tmp\sss\....

**Comment by jrfnl** [comment]
I can confirm this still looks to be an issue on Windows. Running into it as well.

**Comment by theofidry** [comment]
Apologize @tivnet and @jrfnl but I'll have to agree with @TomasVotruba comment on this one.

I'm all up for adding Windows support, but since I don't have much time, don't have Windows and not peculiarly familiar with AppVeyor either, I will not go to great length for it. In other words, if a Windows support will be added, it will be through community support not by me.

If you are willing to help out on the issue, the best thing to do is to try it locally and make it work to provide a PR fixing the issues. To add a better support, I think the best way to go would be to enable AppVeyor on a fork to try to set it up, I could then enable AppVeyor on this repository to ensure the future changes will also work on Windows.

**Comment by jrfnl** [comment]
@theofidry Understood. It's been on my long-term "investigate" list for a few months now. Will try and have a look when I find the time.

I'm inclined to think it should be a relatively easy fix, something along the lines of checking whether `output-dir` has been passed from the command-line, if so, check if it's a relative path and turn it into an absolute path (and make sure the default is an absolute path as well).

Alternatively, this could possibly be fixed by allowing the `output-dir` to be set in the `config` file which would allow users to use `__DIR__` and the likes to create absolute paths themselves.

**Comment by theofidry** [comment]
Thanks for looking into it :)

>Alternatively, this could possibly be fixed by allowing the output-dir to be set in the config file which would allow users to use __DIR__ and the likes to create absolute paths themselves.

I'm fine with that solution, provided (and after a cursory look that shouldn't be an issue) the change stays in `AddPrefixCommand` and does not affect the rest of the application API.

**Comment by jrfnl** [comment]
I'll have a proper look when I have more time. For now, I've used a horrible work-around (copy/paste dir + bits from the autoload file from a linux user) to at least get the project I need it for in a running state, but as you can imagine, that's not a sustainable solution.
