### ISSUE TITLE
PHAR is missing for the 0.6.0 release

### ISSUE THREAD

**Issue by dxops** [humbug/php-scoper#191]
Please build a PHAR and attach it to the 0.6.0 release

**Comment by dxops** [comment]
Thanks @theofidry !

**Comment by sebastianbergmann** [comment]
Maybe the Travis build can be triggered again? That should publish a PHAR for php-scoper 0.6.0, right?

**Comment by theofidry** [comment]
Nope because there was an issue with the Travis config which came after the
release. I’ll do a blank patch release ASAP and hope the Travis config is
fine.

If it’s not I’ll upload a non signed version for now. It is not ideal but
it’s better than nothing and acceptable as long as it’s not for stable
releases

**Comment by theofidry** [comment]
See https://github.com/humbug/php-scoper/releases/tag/0.6.1 :)

**Comment by sebastianbergmann** [comment]
Thanks!

**Comment by sebastianbergmann** [comment]
@kambo-1st php-scoper 0.6.1 is now available as a PHAR.
