### ISSUE TITLE
Add an option to drop comments

### ISSUE THREAD

**Issue by theofidry** [humbug/php-scoper#253]

**Comment by TomasVotruba** [comment]
I had torubles with this features 5/6 years ago with box or some other phar compiler. Some projects use annotations in DI, e.g. Nette with @inject, Symfony with @required, sometimes they're reflecting @return type to get services etc.

It took me days to figure out that packing to phar is failing because 1 annotation was removed. Hell :man_facepalming:

**Comment by theofidry** [comment]
If implemented this should definitely be opt-in and not opt-out to avoid those situations

**Comment by TomasVotruba** [comment]
It was opt-in :D

**Comment by theofidry** [comment]
Since this seems to have low interest I'll drop this for now

**Comment by TomasVotruba** [comment]
Thank you
