### ISSUE TITLE
How to point --output-dir to the same directory

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#297]
Hi, in the beggining I'd like to say I'm glad the work continues :+1: good job!

I'm working on [prefixer for Rector](https://github.com/rectorphp/prefixer) and I have a working directory, where all the build happens.

I need to work and change the `ONE_DIR` only. No copy-ing or moving:

```
vendor/bin/php-scoper add-prefix ONE_DIR --no-interaction --output-dir ONE_DIR
```

This actually creates `ONE_DIR/ONE_DIR` directory :cry: 

```
vendor/bin/php-scoper add-prefix ONE_DIR --no-interaction --output-dir .
```

This actually creates `ONE_DIR` directory in the `cwd()` :cry: 

<br>

Any ideas?

**Comment by theofidry** [comment]
The main reason it works that way is because scoping is not an atomic operation at all hence the use of another new directory.

I see two possible solutions there:

- Extract some logic of the `AddPrefix::scopeFiles()` into a dedicated service which you could use instead of using the command as an external command
- Add a new option to replace the source instead of dumping it in another directory

**Comment by theofidry** [comment]
@TomasVotruba is there anything to do there? I'm not quite sure this should be handled any differently by PHP-Scoper as what you are asking is basically scoping something _in place_ which I'm not too fond of because the whole operation is not atomic.

**Comment by TomasVotruba** [comment]
It was too hard to solve for me, so I left the issue as wont-fix for now, not remembering any clues.

Better close it :)
