### ISSUE TITLE
Pre and Post patchers

### ISSUE THREAD

**Issue by poisa** [humbug/php-scoper#302]
## Feature Request

I was having trouble coming up with a patcher that would match my input regex. After some fiddling I realized why: by the time the patcher closures runs, the original file has already been scoped so the only way to know exactly what your regex should match is by outputting `$contents` and exiting. When the file in question is at the very end of the processed list, debugging a patcher becomes super time consuming. 

Brainstorming here...

1. Wouldn't it make more sense if patchers ran _before_ scoping happens? It would avoid the above problem.
2. Maybe have pre and post patchers that ran before and after scoping?
3. How about having some flag that would ONLY process the file in question (kinda like PHPUnit has a `--filter` flag).
4. How about whitelisting a line number in a specific file? Like "_don't touch `src/file.php` line 49_".

Just a few thoughts. What do you think?

**Comment by theofidry** [comment]
Hi, thanks for sharing your thoughts :)

The workflow of the patchers is:

get original contents -> scope -> apply patchers

The idea is that PHP-Scoper will always be limited/imperfect because of the nature of PHP. So patchers are here to allow you to correct mistakes or what PHP-Scoper couldn't do. Hence it uses the scoped contents.

I don't really see the use case of a pre-patcher since as you see in the flow above, what's before scoping is getting the original contents. So I think it's easier to simply update the original code directly than adding another hook.

>3\. How about having some flag that would ONLY process the file in question

That would be an interesting usability feature. There is a number of things that can be done in PHP-Scoper to make it a bit more friendly as a CLI tool. Whilst I will welcome any PR for it, I don't plan to work on it since I'm lacking time and my personal main use case for PHP-Scoper was with [Box](https://github.com/humbug/box) which does include some of those usability features.

>4\. How about whitelisting a line number in a specific file? Like "_don't touch `src/file.php` line 49_".

That would be nice but I see two issues with it:

- You need to track the content of the original file (regexes or what you do in patchers is very fragile already but it can survive minor file changes, here a simple additional blank line could break everything)
- It is hard to track the file numbers correctly, especially since we parse the file into an AST, add/change/remove statements and then render that AST (regardless of how the original file was formated)

**Comment by theofidry** [comment]
Closing for know. If there is a specific point you still feel strongly about, please do not hesitate to open a new issue about it so we can discuss more on that :)
