### ISSUE TITLE
integrate with composer/packagist release packaging

### ISSUE THREAD

**Issue by drealecs** [humbug/php-scoper#309]
If I'm developing a library, it might happen that it uses other composer libraries.
Some of those composer libraries are going to be used internally only (not exposed on any public API) so we can scope them for release.
AFAIK, right now composer does not have a way to control the package process logic and packages are handled by GitHub/BitBucket by zipping the whole project.
Before tagging a release, we could run a scope-for-release command that will scope some of the required libraries (and other dependencies) that are used internally.
This could be a configuration in composer.json that would be erased after this step, along with the packages from `require` list that have been scoped and will be committed.

I imagine this would reduce the conflicts when a project might use a lot of dependencies that overlap and sometimes contradict.

**Comment by theofidry** [comment]
I believe we discussed a bit of that [here](https://github.com/composer/composer/issues/5390).

However as I stated there: scoping cannot be treated as a magical and transparent process. PHP-Scoper is doing its best to smoothen the process as much as possible, but you will very likely run into issues and require manual patching (via [patchers](https://github.com/humbug/php-scoper#patchers) for example).

For now the easiest way is, if you have a library `acme/foo`, is to published the scoped version under `acme/foo-shim` for example like PHPStand does. Maybe the process could be simplified and the scoped library published as a GitHub artefact and a Composer plugin pick up that instead of the actual source code.

**Comment by drealecs** [comment]
Yes, this issue was all about the simplification of doing it.
I was not talking about phars but any composer package. But now I realize, from my humble experience with maven that this problems is usually needed to be solved at project package level, not library package level.

**Comment by theofidry** [comment]
Closing as there is not much that can be done here on the short-term at least.
