### ISSUE TITLE
Namespaces in strings not being prefixed correctly

### ISSUE THREAD

**Issue by flowdee** [humbug/php-scoper#351]
Prefixing namespaces and classes etc. worked fine except in the following cases inside some vendor files:

`$subclass = '\\Amazon\\ProductAdvertisingAPI\\v1\\Model\\' . $data->{$discriminator};`

`'shippingCharges' => '\\Amazon\\ProductAdvertisingAPI\\v1\\com\\amazon\\paapi5\\v1\\OfferShippingCharge[]'`

`protected static $swaggerTypes = ['bins' => '\\Amazon\\ProductAdvertisingAPI\\v1\\com\\amazon\\paapi5\\v1\\RefinementBin[]',`

Tried to apply a patcher:

```
'patchers' => [
    function (string $filePath, string $prefix, string $contents): string {

        $contents = preg_replace(
            "/'\\\\Amazon\\\\ProductAdvertisingAPI\\\\/",
            "'\\\\MY_PREFIX\\\\Amazon\\\\ProductAdvertisingAPI\\\\",
            $contents
        );

        return $contents;
    },
],
```

but this didn't help either.

Any suggestions?

**Comment by theofidry** [comment]
The first example makes sense since it's a dynamic expression and attempting to prefix those cases would result in more false positives than anything. For the other twos however I suspect it's because of the `[]`.

The patcher should definitely work though. I recommend to:

- only apply it to a provided file though, as otherwise the `preg_match()` you are doing is done on _all_ the files which can be quite expansive (performance wise)
- put a breakpoint and see what is happening.

Maybe you could dump `$contents` in the right file and try to alter it in a temporary file, e.g.:

```
// tmp.php
<?php

$x = <<<'EOF'
dumped $contents here
EOF;

$patched = preg_replace(...);

\var_dump($patched);
```

To more easily experiment with how to patch the desired content. If you are using HumbugBox, you have a `process` command that can help out with that

**Comment by flowdee** [comment]
Tried var_dump but it just displays the original output of the file, including same namespaces updated and the ones mentioned above not.

No idea how to solve this honestly

**Comment by theofidry** [comment]
The issue is likely your preg_match, I can't check atm but have you tried doubling the `\`? `'\\'` is a single backslash and you have two of them but it's a regex so you need to escape them

**Comment by flowdee** [comment]
It seems like only for the second case, the regex isn't working properly? The other lines are being replaced correctly

<img width="1316" alt="Bildschirmfoto_2019-11-06_um_12_44_58" src="https://user-images.githubusercontent.com/2278756/68295734-52595480-0093-11ea-8f6d-ec0f97e83893.png">

**Comment by flowdee** [comment]
the regex pattern should be fine, according to several online test tools

**Comment by theofidry** [comment]
I can't say much there... The patcher works fine: if you return the content it will take it. PHP-Scoper and some other libs heavily rely on this so this 200% works.

The likely point of failure is how you are replacing the string, i.e. from what you said the `preg_replace()`. IMO you should create a little PHP file as per https://github.com/humbug/php-scoper/issues/351#issuecomment-549148921 to try it out without any interference.

By my experience, the main diff with online tools is how the string escape works which might differ and is often a cause of failure

**Comment by theofidry** [comment]
As previous replied, not much I can do there... There is no way the patcher is broken since absolutely nothing could ever work without it so it's bound to be an issue with the regexes themselves and having to escape them correctly. Testing against an only regex matcher and then transposing it to PHP is the best way to go
