### ISSUE TITLE
How to exclude dev-decencies from the build and scoping

### ISSUE THREAD

**Issue by polevaultweb** [humbug/php-scoper#353]
I'm looking to exclude certain packages from scoping process, so they don't end up in the build directory.

For example, I don't want to distribute my WordPress plugin with the `humbug/php-scoper` (or `jetbrains/phpstorm-stubs`) package. 

Currently I am removing them from the `build/vendor` dir after I have performed the scoping and then running ` composer dump-autoload --working-dir build --classmap-authoritative` to remove the package files from the autoloader. 

But that has the undesired effect of removing my custom prefix from the Composer autoloader classes.

Am I missing something obvious?

**Comment by theofidry** [comment]
> I don't want to distribute my WordPress plugin with the humbug/php-scoper

I think this can be simpler if you use the PHPScoper PHAR instead of the dev dependency. The PHAR is scoped, hence will not have any dependency conflict with your code and won't pollute your dependencies either. That said this doesn't entirely solve your problem as there is still the other dev dependencies.

>Currently I am removing them from the build/vendor dir after I have performed the scoping and then running composer dump-autoload --working-dir build --classmap-authoritative to remove the package files from the autoloader.

This should be working, but I believe you are missing the `--no-dev` flag in there.

Alternatively, you could have a Makefile command or bash script to "dump" the scoped version of your library which could be along the lines of:

- copy your project into a directory except for built artefacts (e.g. your `build` or `vendor` directories)
- install your non-dev dependencies only in there (using the `--no-dev` flag when doing `composer install`
- scope only this code (it's cheaper to exclude the dev files _before_ since it makes less files to scope!)
- dump again the scoped code, again mindful of not forgetting the `--no-dev` flag

Another way still would be to use https://github.com/humbug/box. You are not interested in a PHAR per se but Box does a similar process as described above to bundle the code (removing the dev dependencies, scoping the code and dumping the autoloader). So you could build a PHAR and then extract the code from the PHAR (`box extract`) and remove the unnecessary files from there (there is a 1 or 2 files that will have been added to make your bundled code work as a PHAR). In other words, take advantage of the Box mechanism to take care of the faff for you.

Don't hesitate to share  a link of a repo or something if you need more help

**Comment by polevaultweb** [comment]
Thanks @theofidry, I went with copying my composer.json to a new directory, running composer install --no-dev and scoping that vendor directory and copying back to my release directory. Much appreciated.

**Comment by hirasso** [comment]
Is this still the recommended solution? Copying to a dedicated folder, installing via `--no-dev` and copying back?

**Comment by theofidry** [comment]
Indeed
