### ISSUE TITLE
Simple example with Faker library fails (Uncaught InvalidArgumentException: Unable to find provider)

### ISSUE THREAD

**Issue by vielhuber** [humbug/php-scoper#379]
| Question    | Answer
| ------------| ---------------
| Box version | 0.13.1
| PHP version | 7.3.12
| Platform with version | Windows WSL

first install simple composer package:

```
composer require fzaninotto/faker
```

this script works:
```php
<?php
require_once(__DIR__ . '/vendor/autoload.php');
$faker = Faker\Factory::create();
echo $faker->name;
```

now running php-scoper:
```
wget https://github.com/humbug/php-scoper/releases/download/0.13.1/php-scoper.phar
php php-scoper.phar add-prefix --no-config
cd build
composer dump-autoload
```

now the above script returns:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Unable to find provider "Address" with locale "en_US" in .../build/vendor/fzaninotto/faker/src/Faker/Factory.php:42
```

**Comment by theofidry** [comment]
I cannot say without being certain, but PHP being PHP PHP-Scoper _cannot_ provide a guarantee of your scoped code to just be working. There is [limits](https://github.com/humbug/php-scoper#limitations) hence the need to double check and sometimes [fix it](https://github.com/humbug/php-scoper#patchers) unless the upstream code can be changed to be more "scopeable".

I'll be closing this one for now, because it really requires to look into what is causing the failure and it's not necessarily a bug in PHP-Scoper and I cannot afford to dig into why this arbitrary library is not scoped properly. If you find that the root issue is a bug, do open another issue with it!
