### ISSUE TITLE
Typehinted params get fully qualified namespace even though there's a use statement

### ISSUE THREAD

**Issue by dugajean** [humbug/php-scoper#395]
## Bug report

| Question    | Answer
| ------------| ---------------
| Scoper version | ^0.13.2
| PHP version | 7.3
| Platform with version | macOS
| Github Repo | - 

```
<?php

namespace My\CurrentNs;

use My\Fully\Qualified\Namespaced\Class;

class MyClass {

	public function __construct(\My\Fully\Qualified\Namespaced\Class $foo) {
		$foo->doSomething()
	}
```

Why does the constructor param have `\My\Fully\Qualified\Namespaced\Class` typehint when there's an import covering that? This is creating inconsistencies in my code.

Is there a config to fix this? Or is this a bug?

**Comment by theofidry** [comment]
This is expected. Dealing with non fully-qualified names is tedious, you sometimes have a relative name, sometimes an absolute, sometimes with a use statement, partial use statement, alias...

To simplify that: PHP-Scoper just systematically replaces a symbol to its fully qualified form. This allows to simplify things on PHP-Scoper end and since the scoped code is not meant to be developed upon but simply consumed, it is ok if it looks a bit more obfuscated. It would also be simple from there to reformat it to your needs via PHP-CS-Fixer or other
