### ISSUE TITLE
php-scoper requires PHP 8 as minimum

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#449]
Hi Theo,
thank you for continuous work on scoper and very quick PHP 8 support!

I have troubles running 0.14 on non-PHP 8 version.

When I download the package:

```bash
wget https://github.com/humbug/php-scoper/releases/download/0.14.0/php-scoper.phar -N
```

I get following error. This function is from PHP 8 or Symfony PHP 8 polyfill:

https://github.com/rectorphp/rector/pull/4559/checks?check_run_id=1597181880#step:4:359

![image](https://user-images.githubusercontent.com/924196/102933688-fde58400-44a2-11eb-929f-10614f8d27da.png)

I need to run scoper on PHP 7.3. What should I do?

**Comment by smoench** [comment]
Hi Tomas,

this might be related to https://github.com/humbug/php-scoper/issues/440.

But since it is affecting php-scoper itself I was wondering why the CI hasn't failed and had a look in code.

As your stack trace tells `get_debug_type` is being used for rendering a throwable.
So I think there might be an issue with your scoper configuration file. There are two options to verify this. One would be downgrading php-scoper to version 0.13.10 or the other option would be running that build workflow with PHP 8.0 instead.

**Comment by TomasVotruba** [comment]
Hi, I've done the 1st approach right after I've created this issue. [I've downgraded](https://github.com/rectorphp/rector/pull/4559/commits/901fa777cbedfc97bb72c10fdc87518c390301f3) to 0.13.10 and it works ok.

**Comment by bytestream** [comment]
For some reason `symfony/polyfill-php80` is not being loaded correctly, otherwise `get_debug_type` would be present on PHP 7.x

This should be replicable by setting `--output-dir=.` which generates:
`Failed to remove directory`
