### ISSUE TITLE
Add native support for Symfony PSR-4 autodiscovery for Symfony PHP config

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#451]
Hi,

I'm using scoped to prefix @rectorphp and one of dependencies is using [Symfony PSR-4 autodiscovery](https://symfony.com/blog/new-in-symfony-3-3-psr-4-based-service-discovery) configs - plain PHP files.

The classes in configs are prefixI've notice the namespaced is skipped

```diff
 // correct!
-use SomeNamespace\SomeClass;
+use Prefix1234\SomeNamespace\SomeClass;
 
 return static function (ContainerConfigurator $containerConfigurator) {
     $services = $containerConfigurator->services();

     // incorrect - this should be prefixed too
     $services->load('SomeNamespace\ConsoleColorDiff\\', __DIR__ . '/../src');

     $services->set(SomeClass::class);
 }
```

Now I have to handle this case manually:

```diff
-     $services->load('SomeNamespace\ConsoleColorDiff\\', __DIR__ . '/../src');
+     $services->load('Prefix1234\\SomeNamespace\ConsoleColorDiff\\', __DIR__ . '/../src');
```

I think I might help to contribute this feature. Any starting point where should I add a test fixture for it?

**Comment by theofidry** [comment]
Hi!

I think there is two places where this could be done:

- As a patcher, see. https://github.com/humbug/php-scoper/blob/9afbe0fb4f6ef58024233ea738a529b2f80886bb/src/Patcher/SymfonyPatcher.php
- As a custom scoper (e.g. https://github.com/humbug/php-scoper/blob/9afbe0fb4f6ef58024233ea738a529b2f80886bb/src/Scoper/SymfonyScoper.php)

I think the first option would work best since it might be easier to capture via a regex. The danger though is how it might affect the scoping process in general including outside of Symfony apps. But to mitigate that I think there could be two solutions:

- Adding a config entry to say "this is a Symfony app"
- Expose the patcher you will write so that it's not registered by default but you still can easily add it to the list of patchers manually

Those solutions could be done later though if it becomes necessary
