### ISSUE TITLE
0.16.2@a14eec9 scopes global constants where 0.15.0 did not

### ISSUE THREAD

**Issue by sebastianbergmann** [humbug/php-scoper#639]
This new behaviour breaks PHPUnit's process isolation feature when PHPUnit is run from a scoped PHAR.

#### PHP-Scoper 0.16.2@a14eec9
```
$ ./tools/php-scoper --version
PhpScoper version 0.16.2@a14eec9 2022-02-05 21:48:04 UTC
```
```
$ ack __PHPUNIT_PHAR__ build/artifacts/phpunit-snapshot.phar
define('__PHPUNIT_PHAR__', str_replace(DIRECTORY_SEPARATOR, '/', __FILE__));
        if (defined('PHPUnit\\__PHPUNIT_PHAR__')) {
            $prefix = 'phar://' . __PHPUNIT_PHAR__ . '/';
        if (defined('PHPUnit\\__PHPUNIT_PHAR__')) {
            $phar = var_export(__PHPUNIT_PHAR__, \true);
            if (defined('PHPUnit\\__PHPUNIT_PHAR__')) {
                $phar = var_export(__PHPUNIT_PHAR__, \true);

```
#### PHP-Scoper 0.15.0
```
$ ./tools/php-scoper --version                                                  
PHP Scoper version 0.15.0 2021-05-10 21:02:42 UTC
```
```
$ ack __PHPUNIT_PHAR__ build/artifacts/phpunit-snapshot.phar 
define('__PHPUNIT_PHAR__', str_replace(DIRECTORY_SEPARATOR, '/', __FILE__));
        if (defined('__PHPUNIT_PHAR__')) {
            $prefix = 'phar://' . __PHPUNIT_PHAR__ . '/';
        if (defined('__PHPUNIT_PHAR__')) {
            $phar = var_export(__PHPUNIT_PHAR__, \true);
            if (defined('__PHPUNIT_PHAR__')) {
                $phar = var_export(__PHPUNIT_PHAR__, \true);
```

**Comment by theofidry** [comment]
I'll be honest, I don't understand why this was working before 😅 

For records, here's the PHP-Scoper config:

```php
return [
    'whitelist' => [
        'PHPUnit\*',
    ],
    'patchers' => [
        static function (string $filePath, string $prefix, string $content): string
        {
            // scoper_replace_function is a custom function, remove the declaration as it is not an interesting part here
            return scoper_replace_function($prefix, $content, 'xdebug_info');
        },
    ],
];
```

So first of, totally unrelated to the issue at hand but this should be migrated:

- `xdebug_info` is now available within PHP-Scoper as an internal symbol hence the patcher can be removed
- in the future if a similar case to `xdebug_info` arise, `exclude-functions => ['xdebug_info']` should do the trick
- the `whitelist` entry is deprecated (dunno how to log that to the user without messing up all my tests... >.>) and should in your case be equivalent to `exclude-namespaces => ['PHPUnit']`.

So in that regard, here's the updated config:

```php
return [
    'exclude-namespaces' => [
        'PHPUnit',
    ],
];
```

Now for the `__PHPUNIT_PHAR__` and similar others I am confused as none of the config here touches them: they are from the global namespace and whether global symbols are exposed by default has not changed.

That being said, in your case I think you can to declare those symbols as exposed. If you wonder whether something should be exposed or excluded, as a rule of thumb if the symbol comes from a third-party API you can no control over (e.g. for a WP plugin the WP API or symbols coming from a PHP extension), the `exclude` is the answer. If it is something from you but to expose to the user then it should be `expose`. So in theory even your `exclude-namespaces` should ideally be `expose-namespaces`. But I think just changing this like that may not work right away as there is limitations to exposing elements (e.g. traits or enums which cannot be aliased).

With that in mind, I think in your case you want to expose those PHPUnit specific constants and for that a regex could work well (rather than blindly exposing any global constant):

```php
return [
    'exclude-namespaces' => [
        'PHPUnit',
    ],
    'expose-constants' => [
        '/^__PHPUNIT_.+$/'
    ],
];
```

**Comment by sebastianbergmann** [comment]
Thank you!
