### ISSUE TITLE
allow specifiying included-namespaces rather than just ones to exclude

### ISSUE THREAD

**Issue by diosmosis** [humbug/php-scoper#844]
## Feature Request

I have the need to prefix a set of namespaces while ignoring all others, but currently there is only the set of `excluded-...` options.

A new option `included-namespaces` that only prefixes the given namespace (and every namespace contained within) would be useful. I think the option should not end up excluding the global namespace.

I'd be happy to create a PR if this is deemed a useful addition.

**Comment by theofidry** [comment]
Hi, what would be the use case exactly?

The idea of prefixing is to prefix as much as possible. In that sense providing the exhaustive list of what can be prefixed sounds counter-productive at first.

**Comment by diosmosis** [comment]
I needed to prefix a large piece of software with more than 29 dependencies, not every dependency needs to be prefixed (only a couple require it at the moment), and it is much easier in the long run to just prefix one of them (at a time and when actually needed) to reduce the possibility users will experience bugs from the process.

**Comment by theofidry** [comment]
Could that work with a negation regex?

**Comment by diosmosis** [comment]
Possibly, but I think that might also exclude the global namespace, which I wouldn't want. For example, if I exclude everything that doesn't match `/^Twig\\$/`, then the global `twig_...` functions wouldn't match and wouldn't be prefixed.

**Comment by diosmosis** [comment]
Oh maybe a regex that allowed empty strings might work there. I'd have to check.

**Comment by diosmosis** [comment]
I won't have time to check whether the use of a negation regex works in this case as I was able to add the functionality in a fork, but I can think of a couple possible problems with the approach:

* if there are multiple namespaces to include, the regex will become harder to read, especially in contrast to just `'include-namespaces' => ['MyNamespace1', 'MyNamespace2\A', ...etc.]`
* for more complicated uses mixing excludes/includes, like `include A\*`, `exclude A\B*`, `exclude A\C\D\*` using a regex would be complicated and likely error prone (using a regex to express boolean logic does not seem ideal)

Anyway, since I have this functionality in a fork, feel free to close this issue if you'd like.

**Comment by theofidry** [comment]
We can leave the issue open for a while see if there is any interest.

In the current state of things I am reluctant because this kinda goes against the idea of the tool which is to scope as much as possible.

However this could be me being too narrow-minded, so I am happy to see if there is a demand for such a feature.

**Comment by theofidry** [comment]
Since it's been a while since this PR has been opened and no one came forward I'll be closing this for now.

I will however add: currently this feature can be achieved with PHP-Scoper natively using a script to collect the symbols to exclude or expose. It is what is done for [Wordpress plugins](https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#wordpress-support) or in [PHPUnit to list the symbols containing the `@internal` tag](https://github.com/sebastianbergmann/phpunit/commit/05f57ade9b823a48153f7bb2bdec006a9bb303c8).

If however someone feels like this feature should be added and want to discuss about it again, feel free to open a new issue about it.
