### ISSUE TITLE
Optionally group patchers to run iterations over all files

### ISSUE THREAD

**Issue by kkmuffme** [humbug/php-scoper#863]
## Feature Request

Currently, all patchers will run for one file after another. e.g. with 2 files a and b.php and 2 patcher functions it would run the patchers like:

a.php
a.php
b.php
b.php

```
 'patchers' => [
    static function () { ... },
    static function () { ... },
],
 ```

In some cases, the things to patch in a file depend on each other - e.g. I need to patch something in a.php that depends on something in b.php (similar to how composer generates a hash for the autoloader function name)

It would be great if either
a) the default behavior could be changed (so the above would run a.php, b.php, a.php, b.php) - as a flag perhaps?
or (probably better)
b) we could optionally group patchers like this:

```
 'patchers' => [
     [
        static function () { ... },
        static function () { ... },
    ],
     [
        static function () { ... },
        static function () { ... },
    ],    
],
 ```
 
Which would run:
a.php
a.php
b.php
b.php
a.php
a.php
b.php
b.php

There currently is a workaround by collecting those file names in a closure and then reading/modifying/writing them with again with the last file in the list, but it's unnecessary slow bc of those additional read/write operations and also makes the code really verbose.

**Comment by theofidry** [comment]
Could you expend on the use case?

I was thinking of changing the patchers to allow to handle an array of files in some cases, however even that wouldn't suit your current scenario.

Another problem too is that for example with Box, the processing can be done in parallel. That and the file order is very prone to change from one machine to another too.

**Comment by theofidry** [comment]
>which means at the time the patcher runs a.php I do not know the name of the constant/function from b.php yet.

Wouldn't it make more sense to generate a deterministic name beforehand?

>This isn't a problem as you can just run all patchers of a group (array) in parallel just like now (just not all groups in parallel of course)

It's more of a problem that a.php can be done in processA and b.php in processB.

**Comment by theofidry** [comment]
Coming back to this, I am sorry to say but the whole ordeal sounds too much of an edge case to support out of the Box.

I had a deeper look in the design and this is really not a light change by any means. It completely breaks the current API/flow both at various levels and including in Box, because the current design in mind is one file one process, i.e. no dependencies between two files.

That being said, I also understand this can be needed and I also don't want to prevent you to achieve this completely either. Maybe there is easier ways to solve this problem?

I can think of 3 solutions:

1. Sketchy patcher operations (which is what you're doing from what I understood).
2. A fork of PHP-Scoper or requiring it as a library and re-implement the add-prefix command, where you apply this change. In which case the least minimal change I think would be two passes rather than one.
3. An after scoping script. Probably the best solution? In the end you still have extra steps to do after a scoping process like dumping the autoload. As such maybe within the scoping process, via a patcher, you could fit in a temporary value, which you search & replace once after (be it via a PHP script or a bash command?).

If 2) would work better in your case I'm happy to review how you're doing it in order to find a way that would minimise the amount of modifications you have to do to make it more sustainable.
