### ISSUE TITLE
Patcher additional arg for progress

### ISSUE THREAD

**Issue by kkmuffme** [humbug/php-scoper#878]
## Feature Request

It's kind of inspired by https://github.com/humbug/php-scoper/issues/302 - basically a "post" patcher or alternatively an additional argument in the existing patcher that contains the number of patched files vs how many are left to go, so I can run some code when the last file gets patched.

Basically, I need to do a few misc tasks after patching is done and I'd like to do all of that from the scoper config file directly instead of having to write another wrapper/bash script to call another PHP file when scoping is done.

**Comment by theofidry** [comment]
Hi,

I've given it more thoughts and will not include such a feature. The reason being that:

- If you are using PHP-Scoper directly, you most likely already have extra step(s) to do after executing PHP-Scoper, for instance dumping the Composer autoloader.
- Other projects, like Box, support parallelism in which case knowing the progress of the processes files is tricky. The only reason it would not be a problem in PHP-Scoper right now is because there is no parallel processing yet, but more out of laziness on my end than an architectural decision. So this could change anytime if someone wants to add it
