### ISSUE TITLE
Document CLI arg (inspect)

### ISSUE THREAD

**Issue by kkmuffme** [humbug/php-scoper#925]
Could you please document the undocumented CLI args (e.g. inspect) with a short example in the readme, as that would be really helpful for most people I guess.
Would really appreciate that!

Btw. there's a little spelling mistake in some files `scopped` => `scoped` you might want to fix

**Comment by theofidry** [comment]
Apologies for the late reply somehow I missed your issue.

>Could you please document the undocumented CLI args (e.g. inspect) with a short example in the readme, as that would be really helpful for most people I guess.

The list of commands can be found by calling `php-scoper` or calling the `list` command: `php-scoper list`. Then if you want more details for any command you can always do `php-scoper help <commandName>` or `php-scoper <commandName> --help`.

For the `inspect` command:

```
Description:
  Outputs the processed file content based on the configuration.

Usage:
  inspect [options] [--] <file-path>

Arguments:
  file-path                      The file path to process.

Options:
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
  -p, --prefix=PREFIX            The namespace prefix to add. [default: ""]
  -c, --config=CONFIG            Configuration file. Will use "scoper.inc.php" if found by default.
      --no-config                Do not look for a configuration file.
  -h, --help                     Display help for the given command. When no command is given display help for the list command
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi|--no-ansi           Force (or disable --no-ansi) ANSI output
  -n, --no-interaction           Do not ask any interactive question
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

```

That being said, you are right that a little mention would be nice still, I opened #925 for it.

>Btw. there's a little spelling mistake in some files scopped => scoped you might want to fix

Thanks, fixed in #976!
