### ISSUE TITLE
Namespaces not properly working after using php-scoper

### ISSUE THREAD

**Issue by bilal-ahmed-wpb** [humbug/php-scoper#948]
My plugin Analytify was having conflict with the other plugin if it was using google library in Wordpress. Previously my vendor folder was namespace by prefix Analytify using php-scoper excluding the namespaces Composer, Grpc and Google I worked around the solution and then I exclude three more namespaces that were Guzzlehttp, Monology, and Psr and by this the conflict was totally resolved. But now I was making the entire vendor namespace to Analytify so that it is totally containerized but then I get following errors in my plugin and I have looked into them and all the mentioned classes are properly namespace by Analytify but it is saying not found. The errors are:

WARNING Analytify\Google\Analytics\Admin\V1alpha\DataStream is not found in descriptor pool. Only generated classes may derive from Message

WARNING Analytify\Google\Analytics\Admin\V1alpha\ListDataStreamsRequest is not found in descriptor pool

WARNING (query) missing required param: 'siteUrl'

WARNING Analytify\Google\Analytics\Admin\V1alpha\ListAccountsRequest is not found in descriptor pool

WARNING Analytify\Google\Analytics\Admin\V1alpha\ListAccountsRequest is not found in descriptor pool

Now I want a way to solve this because I have checked the classes are namespace properly but it is showing not found. Any clue to fix it?

My scoper.inc.php file is

<?php

declare (strict_types=1);
namespace Analytify;

// scoper.inc.php
use Analytify\Isolated\Symfony\Component\Finder\Finder;
return [
    'prefix' => 'Analytify',
    // string|null
    'output-dir' => null,
    // string|null
    'finders' => [],
    // list<Finder>
    'patchers' => [],
    // list<callable(string $filePath, string $prefix, string $contents): string>
    'exclude-files' => [],
    // list<string>
    'exclude-namespaces' => [],
    // list<string|regex>
    'exclude-constants' => [],
    // list<string|regex>
    'exclude-classes' => [],
    // list<string|regex>
    'exclude-functions' => [],
    // list<string|regex>
    'expose-global-constants' => \false,
    // bool
    'expose-global-classes' => \false,
    // bool
    'expose-global-functions' => \false,
    // bool
    'expose-namespaces' => [],
    // list<string|regex>
    'expose-constants' => [],
    // list<string|regex>
    'expose-classes' => [],
    // list<string|regex>
    'expose-functions' => [],
];

Also a guidance needed that is excluding the namespaces on which error occurs is better or just namespace entire vendor that contains Google Libraries for php

**Comment by bilal-ahmed-wpb** [comment]
I have two plugins Analytify and Loginpress. In Loginpress Plugin when I configure my social login as Google (Login as Google), I get following error:

Fatal error: Uncaught Error: Google\Auth\HttpHandler\HttpHandlerFactory::build(): Argument #1 ($client) must be of type ?GuzzleHttp\ClientInterface, Analytify\GuzzleHttp\Client given, called in C:\Users\WPB\Local Sites\analytify-google-login\app\public\wp-content\plugins\wp-analytify\lib\Google-GA4\vendor\google\apiclient\src\Client.php on line 220 in C:\Users\WPB\Local Sites\analytify-google-login\app\public\wp-content\plugins\loginpress-pro\addons\social-login\sdk\google-client\vendor\google\auth\src\HttpHandler\HttpHandlerFactory.php on line 34

I have worked on this by changing the Analytify\GuzzleHttp\Client to GuzzleHttp\Client on which class already declared comes up. I have namespace using php-scoper but still the issue presists

**Comment by theofidry** [comment]
Hi, unfortunately it is a bit hard to tell without seeing the code.

The feeling I get from your issue is that your tried PHP-Scoper, and the result is non working PHP code. This is likely due to a piece of code that was not scoped correctly and it is unfortunately expected to some degree. PHP is a very permissive and exotic language, scoping is by no means an easy process, so there is bound to be cases that need to be manually corrected, for example via [patchers](https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#patchers).

From my limited experience with Google PHP libraries, they rely a lot on magic methods so I would not be surprised that it does not work out of the box.

If you have more specific issues please open issues for them, but otherwise I have no solution for this issue besides "look at the scoped code and correct it". If there is something very wrong that can be fixed within PHP-Scoper this can be addressed in a dedicated issue, but it is otherwise within the realm of having to fix it by hand.

**Comment by bilal-ahmed-wpb** [comment]
> Hi, unfortunately it is a bit hard to tell without seeing the code.
> 
> The feeling I get from your issue is that your tried PHP-Scoper, and the result is non working PHP code. This is likely due to a piece of code that was not scoped correctly and it is unfortunately expected to some degree. PHP is a very permissive and exotic language, scoping is by no means an easy process, so there is bound to be cases that need to be manually corrected, for example via [patchers](https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#patchers).
> 
> From my limited experience with Google PHP libraries, they rely a lot on magic methods so I would not be surprised that it does not work out of the box.
> 
> If you have more specific issues please open issues for them, but otherwise I have no solution for this issue besides "look at the scoped code and correct it". If there is something very wrong that can be fixed within PHP-Scoper this can be addressed in a dedicated issue, but it is otherwise within the realm of having to fix it by hand.

So how I look into the vast library and then use the patcher? As there are over 1500 files

**Comment by theofidry** [comment]
An example, I have an integration test where I can use `bin/php-scoper`. An easy way to check if the scoped code works is to swap `bin/php-scoper` for `bin/php-scoper.phar` in that test.

For a plugin I assume you could have an integration test where you import this plugin and do something. You could similarly do the same have a test importing the scoped plugin.

Otherwise I would say it is trial and error: you don't go auditing the whole `vendor` to see if everything is scoped properly but rather try to use the scoped code and see if there is any error popping up.
