### ISSUE TITLE
`new static` not respected

### ISSUE THREAD

**Issue by aaemnnosttv** [humbug/php-scoper#99]
Hey guys,

Ran into an issue today where `new static(...)` is translated to `new Prefix\static(...)`, where it shouldn't be prefixed at all.

Here's an example using an example from Guzzle: [php-scoper-issue.zip](https://github.com/humbug/php-scoper/files/1318940/php-scoper-issue.zip)

Comparing the src and build files you can see this

```diff
@@ -47,21 +41,12 @@
      */
     public static function factory($config = array())
     {
-        return new static(isset($config['base_url']) ? $config['base_url'] : null, $config);
-    }
-
+        return new \Prefix\Guzzle\Service\static(isset($config['base_url']) ? $config['base_url'] : null, $config);
+    }
```

The command I ran here was 

```
php-scoper add-prefix --prefix="Prefix\\" src/
```

php-scoper@227a4fd

Anything I can do to help out here?

**Comment by aaemnnosttv** [comment]
Hey guys, I installed a version a few commits back 72182d9357e4b9c7cd11de6da96c0206b0752054 and it doesn't have this problem.

I also noticed that the above newer version inlined the fully qualified class name all over the place, such as type hints where it had already been imported. Is this intentional?

**Comment by theofidry** [comment]
Indeed I noticed this issue as well. I'll try to do a patch for it soonish.

I've done quite some significant changes since the last release. It's not really over yet so I would recommend to use the latest release rather than dev-master :)

Regarding your question: yes this is intentional. The rational is that it's way easier to deal with FQCN to know whether or not to prefix or if the class is whitelisted or something. So even though it's a bit uglier, it still stays readable and removes a lot of complexity or edge cases.
